/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phoenixpen_desktop_application_X11Wrapper */

#ifndef _Included_com_phoenixpen_desktop_application_X11Wrapper
#define _Included_com_phoenixpen_desktop_application_X11Wrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_phoenixpen_desktop_application_X11Wrapper
 * Method:    raiseWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_phoenixpen_desktop_application_X11Wrapper_raiseWindow
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
